package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.Blobable;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;

import java.util.Date;
@Table("player_msg")
public class PlayerMsg implements Blobable<Entity.PlayerMsgBlob>
{
    public Entity.PlayerMsgBlob toBlob()
    {
        Entity.PlayerMsgBlob.Builder blob = Entity.PlayerMsgBlob.newBuilder();
        blob.setPlayerId(playerId);
        blob.setFromType(fromType);
        blob.setContent(content);
        blob.setMsgTime(msgTime.getTime());
        return blob.build();
    }
    public void fromBlob(Entity.PlayerMsgBlob blob)
    {
        this.playerId = blob.getPlayerId();
        this.fromType = blob.getFromType();
        this.content = blob.getContent();
        this.msgTime = new Date(blob.getMsgTime());
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_msg.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_msg.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_msg.from_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "from_type")
    private Integer fromType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_msg.content
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "content")
    private String  content;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_msg.msg_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "msg_time")
    private Date msgTime = new Date();
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_msg.id
     *
     * @return the value of player_msg.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_msg.id
     *
     * @param id the value for player_msg.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_msg.player_id_
     *
     * @return the value of player_msg.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_msg.player_id_
     *
     * @param playerId the value for player_msg.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_msg.from_type
     *
     * @return the value of player_msg.from_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getFromType()
    {
        return fromType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_msg.from_type
     *
     * @param fromType the value for player_msg.from_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setFromType(Integer fromType)
    {
        this.fromType = fromType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_msg.content
     *
     * @return the value of player_msg.content
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public String getContent()
    {
        return content;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_msg.content
     *
     * @param content the value for player_msg.content
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setContent(String content)
    {
        this.content = content == null ? null : content.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_msg.msg_time
     *
     * @return the value of player_msg.msg_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Date getMsgTime()
    {
        return msgTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_msg.msg_time
     *
     * @param msgTime the value for player_msg.msg_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setMsgTime(Date msgTime)
    {
        this.msgTime = msgTime;
    }
}