package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.Blobable;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;

import java.util.Date;
@Table("player_recharge")
public class PlayerRecharge implements Blobable<Entity.PlayerRechargeBlob>
{
    public Entity.PlayerRechargeBlob toBlob()
    {
        Entity.PlayerRechargeBlob.Builder blob = Entity.PlayerRechargeBlob.newBuilder();
        blob.setPlayerId(playerId);
        blob.setTotalAmount(totalAmount);
        blob.setLastOpTime(lastOpTime.getTime());
        blob.setVer(ver);
        return blob.build();
    }
    public void fromBlob(Entity.PlayerRechargeBlob blob)
    {
        this.playerId = blob.getPlayerId();
        this.totalAmount = blob.getTotalAmount();
        this.lastOpTime = new Date(blob.getLastOpTime());
        this.ver = blob.getVer();
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recharge.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recharge.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recharge.total_amount
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "total_amount")
    private Integer totalAmount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recharge.last_op_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "last_op_time")
    private Date lastOpTime = new Date();
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recharge.ver
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "ver")
    private Integer ver;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recharge.id
     *
     * @return the value of player_recharge.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recharge.id
     *
     * @param id the value for player_recharge.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recharge.player_id_
     *
     * @return the value of player_recharge.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recharge.player_id_
     *
     * @param playerId the value for player_recharge.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recharge.total_amount
     *
     * @return the value of player_recharge.total_amount
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getTotalAmount()
    {
        return totalAmount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recharge.total_amount
     *
     * @param totalAmount the value for player_recharge.total_amount
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setTotalAmount(Integer totalAmount)
    {
        this.totalAmount = totalAmount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recharge.last_op_time
     *
     * @return the value of player_recharge.last_op_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Date getLastOpTime()
    {
        return lastOpTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recharge.last_op_time
     *
     * @param lastOpTime the value for player_recharge.last_op_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setLastOpTime(Date lastOpTime)
    {
        this.lastOpTime = lastOpTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recharge.ver
     *
     * @return the value of player_recharge.ver
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getVer()
    {
        return ver;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recharge.ver
     *
     * @param ver the value for player_recharge.ver
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setVer(Integer ver)
    {
        this.ver = ver;
    }
}