package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;
@Table("player_fabao_frag")
public class PlayerFabaoFrag
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_fabao_frag.id
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_fabao_frag.player_id_
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_fabao_frag.fabao_frag_id_
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    @Column(name = "fabao_frag_id")
    private Integer fabaoFragId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_fabao_frag.fabao_frag_amt
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    @Column(name = "fabao_frag_amt")
    private Integer fabaoFragAmt;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_fabao_frag.logical_server_id
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    @Column(name = "logical_server_id")
    private Integer logicalServerId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_fabao_frag.id
     *
     * @return the value of player_fabao_frag.id
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_fabao_frag.id
     *
     * @param id the value for player_fabao_frag.id
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_fabao_frag.player_id_
     *
     * @return the value of player_fabao_frag.player_id_
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_fabao_frag.player_id_
     *
     * @param playerId the value for player_fabao_frag.player_id_
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_fabao_frag.fabao_frag_id_
     *
     * @return the value of player_fabao_frag.fabao_frag_id_
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public Integer getFabaoFragId()
    {
        return fabaoFragId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_fabao_frag.fabao_frag_id_
     *
     * @param fabaoFragId the value for player_fabao_frag.fabao_frag_id_
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public void setFabaoFragId(Integer fabaoFragId)
    {
        this.fabaoFragId = fabaoFragId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_fabao_frag.fabao_frag_amt
     *
     * @return the value of player_fabao_frag.fabao_frag_amt
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public Integer getFabaoFragAmt()
    {
        return fabaoFragAmt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_fabao_frag.fabao_frag_amt
     *
     * @param fabaoFragAmt the value for player_fabao_frag.fabao_frag_amt
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public void setFabaoFragAmt(Integer fabaoFragAmt)
    {
        this.fabaoFragAmt = fabaoFragAmt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_fabao_frag.logical_server_id
     *
     * @return the value of player_fabao_frag.logical_server_id
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public Integer getLogicalServerId()
    {
        return logicalServerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_fabao_frag.logical_server_id
     *
     * @param logicalServerId the value for player_fabao_frag.logical_server_id
     *
     * @mbggenerated Wed Jul 10 16:49:33 CST 2013
     */
    public void setLogicalServerId(Integer logicalServerId)
    {
        this.logicalServerId = logicalServerId;
    }
}