package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.Blobable;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;

import java.util.Date;
@Table("player_wuxing_raffle_info")
public class PlayerWuxingRaffleInfo implements Blobable<Entity.PlayerWuxingRaffleInfoBlob>
{
    public Entity.PlayerWuxingRaffleInfoBlob toBlob()
    {
        Entity.PlayerWuxingRaffleInfoBlob.Builder blob = Entity.PlayerWuxingRaffleInfoBlob.newBuilder();
        blob.setPlayerId(playerId);
        blob.setRaffleType(raffleType);
        blob.setRemainTimeSpan(remainTimeSpan);
        blob.setDailyRemainFreeTimes(dailyRemainFreeTimes);
        blob.setIsFirstYb(isFirstYb);
        blob.setReqYbAmt(reqYbAmt);
        blob.setCardCntYb(cardCntYb);
        blob.setAccumulateTimes(accumulateTimes);
        blob.setTotalCompensateTimes(totalCompensateTimes);
        blob.setRoundStartDt(roundStartDt.getTime());
        blob.setCreateDt(createDt.getTime());
        blob.setLastUpdateDt(lastUpdateDt.getTime());
        blob.setLogicalServerId(logicalServerId);
        return blob.build();
    }
    public void fromBlob(Entity.PlayerWuxingRaffleInfoBlob blob)
    {
        this.playerId = blob.getPlayerId();
        this.raffleType = blob.getRaffleType();
        this.remainTimeSpan = blob.getRemainTimeSpan();
        this.dailyRemainFreeTimes = blob.getDailyRemainFreeTimes();
        this.isFirstYb = blob.getIsFirstYb();
        this.reqYbAmt = blob.getReqYbAmt();
        this.cardCntYb = blob.getCardCntYb();
        this.accumulateTimes = blob.getAccumulateTimes();
        this.totalCompensateTimes = blob.getTotalCompensateTimes();
        this.roundStartDt = new Date(blob.getRoundStartDt());
        this.createDt = new Date(blob.getCreateDt());
        this.lastUpdateDt = new Date(blob.getLastUpdateDt());
        this.logicalServerId = blob.getLogicalServerId();
    }
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.id
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.player_id_
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.raffle_type
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "raffle_type")
    private Integer raffleType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.remain_time_span
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "remain_time_span")
    private Integer remainTimeSpan;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.daily_remain_free_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "daily_remain_free_times")
    private Integer dailyRemainFreeTimes;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.is_first_yb
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "is_first_yb")
    private Boolean isFirstYb;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.req_yb_amt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "req_yb_amt")
    private Integer reqYbAmt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.card_cnt_yb
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "card_cnt_yb")
    private Integer cardCntYb;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.accumulate_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "accumulate_times")
    private Integer accumulateTimes;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.total_compensate_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "total_compensate_times")
    private Integer totalCompensateTimes;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.round_start_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "round_start_dt")
    private Date roundStartDt = new Date();
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.create_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "create_dt")
    private Date createDt     = new Date();
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.last_update_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "last_update_dt")
    private Date lastUpdateDt = new Date();
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_wuxing_raffle_info.logical_server_id
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    @Column(name = "logical_server_id")
    private Integer logicalServerId;
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.id
     * @return the value of player_wuxing_raffle_info.id
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.id
     * @param id  the value for player_wuxing_raffle_info.id
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.player_id_
     * @return the value of player_wuxing_raffle_info.player_id_
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.player_id_
     * @param playerId  the value for player_wuxing_raffle_info.player_id_
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.raffle_type
     * @return the value of player_wuxing_raffle_info.raffle_type
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getRaffleType()
    {
        return raffleType;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.raffle_type
     * @param raffleType  the value for player_wuxing_raffle_info.raffle_type
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setRaffleType(Integer raffleType)
    {
        this.raffleType = raffleType;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.remain_time_span
     * @return the value of player_wuxing_raffle_info.remain_time_span
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getRemainTimeSpan()
    {
        return remainTimeSpan;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.remain_time_span
     * @param remainTimeSpan  the value for player_wuxing_raffle_info.remain_time_span
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setRemainTimeSpan(Integer remainTimeSpan)
    {
        this.remainTimeSpan = remainTimeSpan;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.daily_remain_free_times
     * @return the value of player_wuxing_raffle_info.daily_remain_free_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getDailyRemainFreeTimes()
    {
        return dailyRemainFreeTimes;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.daily_remain_free_times
     * @param dailyRemainFreeTimes  the value for player_wuxing_raffle_info.daily_remain_free_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setDailyRemainFreeTimes(Integer dailyRemainFreeTimes)
    {
        this.dailyRemainFreeTimes = dailyRemainFreeTimes;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.is_first_yb
     * @return the value of player_wuxing_raffle_info.is_first_yb
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Boolean getIsFirstYb()
    {
        return isFirstYb;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.is_first_yb
     * @param isFirstYb  the value for player_wuxing_raffle_info.is_first_yb
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setIsFirstYb(Boolean isFirstYb)
    {
        this.isFirstYb = isFirstYb;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.req_yb_amt
     * @return the value of player_wuxing_raffle_info.req_yb_amt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getReqYbAmt()
    {
        return reqYbAmt;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.req_yb_amt
     * @param reqYbAmt  the value for player_wuxing_raffle_info.req_yb_amt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setReqYbAmt(Integer reqYbAmt)
    {
        this.reqYbAmt = reqYbAmt;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.card_cnt_yb
     * @return the value of player_wuxing_raffle_info.card_cnt_yb
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getCardCntYb()
    {
        return cardCntYb;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.card_cnt_yb
     * @param cardCntYb  the value for player_wuxing_raffle_info.card_cnt_yb
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setCardCntYb(Integer cardCntYb)
    {
        this.cardCntYb = cardCntYb;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.accumulate_times
     * @return the value of player_wuxing_raffle_info.accumulate_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getAccumulateTimes()
    {
        return accumulateTimes;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.accumulate_times
     * @param accumulateTimes  the value for player_wuxing_raffle_info.accumulate_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setAccumulateTimes(Integer accumulateTimes)
    {
        this.accumulateTimes = accumulateTimes;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.total_compensate_times
     * @return the value of player_wuxing_raffle_info.total_compensate_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getTotalCompensateTimes()
    {
        return totalCompensateTimes;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.total_compensate_times
     * @param totalCompensateTimes  the value for player_wuxing_raffle_info.total_compensate_times
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setTotalCompensateTimes(Integer totalCompensateTimes)
    {
        this.totalCompensateTimes = totalCompensateTimes;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.round_start_dt
     * @return the value of player_wuxing_raffle_info.round_start_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Date getRoundStartDt()
    {
        return roundStartDt;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.round_start_dt
     * @param roundStartDt  the value for player_wuxing_raffle_info.round_start_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setRoundStartDt(Date roundStartDt)
    {
        this.roundStartDt = roundStartDt;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.create_dt
     * @return the value of player_wuxing_raffle_info.create_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Date getCreateDt()
    {
        return createDt;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.create_dt
     * @param createDt  the value for player_wuxing_raffle_info.create_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setCreateDt(Date createDt)
    {
        this.createDt = createDt;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.last_update_dt
     * @return the value of player_wuxing_raffle_info.last_update_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Date getLastUpdateDt()
    {
        return lastUpdateDt;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.last_update_dt
     * @param lastUpdateDt  the value for player_wuxing_raffle_info.last_update_dt
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setLastUpdateDt(Date lastUpdateDt)
    {
        this.lastUpdateDt = lastUpdateDt;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_wuxing_raffle_info.logical_server_id
     * @return the value of player_wuxing_raffle_info.logical_server_id
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public Integer getLogicalServerId()
    {
        return logicalServerId;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_wuxing_raffle_info.logical_server_id
     * @param logicalServerId  the value for player_wuxing_raffle_info.logical_server_id
     * @mbggenerated Mon Jul 22 02:02:14 CST 2013
     */
    public void setLogicalServerId(Integer logicalServerId)
    {
        this.logicalServerId = logicalServerId;
    }
}