package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.Blobable;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;

import java.util.Date;
@Table("player_friend")
public class PlayerFriend implements Blobable<Entity.PlayerFriendBlob>
{
    public Entity.PlayerFriendBlob toBlob()
    {
        Entity.PlayerFriendBlob.Builder blob = Entity.PlayerFriendBlob.newBuilder();
        blob.setPlayerId(playerId);
        blob.setFriendId(friendId);
        blob.setEstablishTime(establishTime.getTime());
        blob.setIsAllowGuajiStolen(isAllowGuajiStolen);
        blob.setLogicalServerId(logicalServerId);
        return blob.build();
    }
    public void fromBlob(Entity.PlayerFriendBlob blob)
    {
        this.playerId = blob.getPlayerId();
        this.friendId = blob.getFriendId();
        this.establishTime = new Date(blob.getEstablishTime());
        this.isAllowGuajiStolen = blob.getIsAllowGuajiStolen();
        this.logicalServerId = blob.getLogicalServerId();
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_friend.id
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_friend.player_id_
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_friend.friend_id_
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    @Column(name = "friend_id_")
    private Integer friendId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_friend.establish_time
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    @Column(name = "establish_time")
    private Date establishTime = new Date();
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_friend.is_allow_guaji_stolen
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    @Column(name = "is_allow_guaji_stolen")
    private Boolean isAllowGuajiStolen;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_friend.logical_server_id
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    @Column(name = "logical_server_id")
    private Integer logicalServerId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_friend.id
     *
     * @return the value of player_friend.id
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_friend.id
     *
     * @param id the value for player_friend.id
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_friend.player_id_
     *
     * @return the value of player_friend.player_id_
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_friend.player_id_
     *
     * @param playerId the value for player_friend.player_id_
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_friend.friend_id_
     *
     * @return the value of player_friend.friend_id_
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public Integer getFriendId()
    {
        return friendId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_friend.friend_id_
     *
     * @param friendId the value for player_friend.friend_id_
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public void setFriendId(Integer friendId)
    {
        this.friendId = friendId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_friend.establish_time
     *
     * @return the value of player_friend.establish_time
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public Date getEstablishTime()
    {
        return establishTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_friend.establish_time
     *
     * @param establishTime the value for player_friend.establish_time
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public void setEstablishTime(Date establishTime)
    {
        this.establishTime = establishTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_friend.is_allow_guaji_stolen
     *
     * @return the value of player_friend.is_allow_guaji_stolen
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public Boolean getIsAllowGuajiStolen()
    {
        return isAllowGuajiStolen;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_friend.is_allow_guaji_stolen
     *
     * @param isAllowGuajiStolen the value for player_friend.is_allow_guaji_stolen
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public void setIsAllowGuajiStolen(Boolean isAllowGuajiStolen)
    {
        this.isAllowGuajiStolen = isAllowGuajiStolen;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_friend.logical_server_id
     *
     * @return the value of player_friend.logical_server_id
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public Integer getLogicalServerId()
    {
        return logicalServerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_friend.logical_server_id
     *
     * @param logicalServerId the value for player_friend.logical_server_id
     *
     * @mbggenerated Sun Jul 21 23:44:46 CST 2013
     */
    public void setLogicalServerId(Integer logicalServerId)
    {
        this.logicalServerId = logicalServerId;
    }
}