package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.Blobable;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;

import java.util.Date;
@Table("player_wuxing_card")
public class PlayerWuxingCard implements Blobable<Entity.PlayerWuxingCardBlob>
{
    public Entity.PlayerWuxingCardBlob toBlob()
    {
        Entity.PlayerWuxingCardBlob.Builder blob = Entity.PlayerWuxingCardBlob.newBuilder();
        blob.setName(name);
        blob.setPlayerId(playerId);
        blob.setTplId(tplId);
        blob.setCurExp(curExp);
        blob.setUpgradeExp(upgradeExp);
        blob.setLevel(level);
        blob.setCardGrade(cardGrade);
        blob.setWuxingType(wuxingType);
        blob.setBufType(bufType);
        blob.setBufValue(bufValue);
        blob.setGrowRate(growRate);
        blob.setStarAddRate(starAddRate);
        blob.setStarLevel(starLevel);
        blob.setEquippedWuxingType(equippedWuxingType);
        blob.setIsEquipped(isEquipped);
        blob.setIsEx(isEx);
        blob.setBaseExp(baseExp);
        blob.setUsedExp(usedExp);
        blob.setCreateDt(createDt.getTime());
        blob.setLastUpdateDt(lastUpdateDt.getTime());
        return blob.build();
    }
    public void fromBlob(Entity.PlayerWuxingCardBlob blob)
    {
        this.name = blob.getName();
        this.playerId = blob.getPlayerId();
        this.tplId = blob.getTplId();
        this.curExp = blob.getCurExp();
        this.upgradeExp = blob.getUpgradeExp();
        this.level = blob.getLevel();
        this.cardGrade = blob.getCardGrade();
        this.wuxingType = blob.getWuxingType();
        this.bufType = blob.getBufType();
        this.bufValue = blob.getBufValue();
        this.growRate = blob.getGrowRate();
        this.starAddRate = blob.getStarAddRate();
        this.starLevel = blob.getStarLevel();
        this.equippedWuxingType = blob.getEquippedWuxingType();
        this.isEquipped = blob.getIsEquipped();
        this.isEx = blob.getIsEx();
        this.baseExp = blob.getBaseExp();
        this.usedExp = blob.getUsedExp();
        this.createDt = new Date(blob.getCreateDt());
        this.lastUpdateDt = new Date(blob.getLastUpdateDt());
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.name
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "name")
    private String  name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.tpl_id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "tpl_id")
    private Integer tplId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.cur_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "cur_exp")
    private Integer curExp;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.upgrade_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "upgrade_exp")
    private Integer upgradeExp;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.level
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "level")
    private Integer level;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.card_grade
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "card_grade")
    private Integer cardGrade;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.wuxing_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "wuxing_type")
    private Integer wuxingType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.buf_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "buf_type")
    private Integer bufType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.buf_value
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "buf_value")
    private Float   bufValue;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.grow_rate
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "grow_rate")
    private Float   growRate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.star_add_rate
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "star_add_rate")
    private Float   starAddRate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.star_level
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "star_level")
    private Integer starLevel;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.equipped_wuxing_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "equipped_wuxing_type")
    private Integer equippedWuxingType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.is_equipped
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "is_equipped")
    private Boolean isEquipped;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.is_ex
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "is_ex")
    private Boolean isEx;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.base_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "base_exp")
    private Integer baseExp;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.used_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "used_exp")
    private Integer usedExp;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.create_dt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "create_dt")
    private Date createDt     = new Date();
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_wuxing_card.last_update_dt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "last_update_dt")
    private Date lastUpdateDt = new Date();
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.id
     *
     * @return the value of player_wuxing_card.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.id
     *
     * @param id the value for player_wuxing_card.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.name
     *
     * @return the value of player_wuxing_card.name
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public String getName()
    {
        return name;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.name
     *
     * @param name the value for player_wuxing_card.name
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setName(String name)
    {
        this.name = name == null ? null : name.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.player_id_
     *
     * @return the value of player_wuxing_card.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.player_id_
     *
     * @param playerId the value for player_wuxing_card.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.tpl_id
     *
     * @return the value of player_wuxing_card.tpl_id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getTplId()
    {
        return tplId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.tpl_id
     *
     * @param tplId the value for player_wuxing_card.tpl_id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setTplId(Integer tplId)
    {
        this.tplId = tplId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.cur_exp
     *
     * @return the value of player_wuxing_card.cur_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getCurExp()
    {
        return curExp;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.cur_exp
     *
     * @param curExp the value for player_wuxing_card.cur_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setCurExp(Integer curExp)
    {
        this.curExp = curExp;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.upgrade_exp
     *
     * @return the value of player_wuxing_card.upgrade_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getUpgradeExp()
    {
        return upgradeExp;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.upgrade_exp
     *
     * @param upgradeExp the value for player_wuxing_card.upgrade_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setUpgradeExp(Integer upgradeExp)
    {
        this.upgradeExp = upgradeExp;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.level
     *
     * @return the value of player_wuxing_card.level
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getLevel()
    {
        return level;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.level
     *
     * @param level the value for player_wuxing_card.level
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setLevel(Integer level)
    {
        this.level = level;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.card_grade
     *
     * @return the value of player_wuxing_card.card_grade
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getCardGrade()
    {
        return cardGrade;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.card_grade
     *
     * @param cardGrade the value for player_wuxing_card.card_grade
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setCardGrade(Integer cardGrade)
    {
        this.cardGrade = cardGrade;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.wuxing_type
     *
     * @return the value of player_wuxing_card.wuxing_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getWuxingType()
    {
        return wuxingType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.wuxing_type
     *
     * @param wuxingType the value for player_wuxing_card.wuxing_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setWuxingType(Integer wuxingType)
    {
        this.wuxingType = wuxingType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.buf_type
     *
     * @return the value of player_wuxing_card.buf_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getBufType()
    {
        return bufType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.buf_type
     *
     * @param bufType the value for player_wuxing_card.buf_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setBufType(Integer bufType)
    {
        this.bufType = bufType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.buf_value
     *
     * @return the value of player_wuxing_card.buf_value
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Float getBufValue()
    {
        return bufValue;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.buf_value
     *
     * @param bufValue the value for player_wuxing_card.buf_value
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setBufValue(Float bufValue)
    {
        this.bufValue = bufValue;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.grow_rate
     *
     * @return the value of player_wuxing_card.grow_rate
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Float getGrowRate()
    {
        return growRate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.grow_rate
     *
     * @param growRate the value for player_wuxing_card.grow_rate
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setGrowRate(Float growRate)
    {
        this.growRate = growRate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.star_add_rate
     *
     * @return the value of player_wuxing_card.star_add_rate
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Float getStarAddRate()
    {
        return starAddRate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.star_add_rate
     *
     * @param starAddRate the value for player_wuxing_card.star_add_rate
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setStarAddRate(Float starAddRate)
    {
        this.starAddRate = starAddRate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.star_level
     *
     * @return the value of player_wuxing_card.star_level
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getStarLevel()
    {
        return starLevel;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.star_level
     *
     * @param starLevel the value for player_wuxing_card.star_level
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setStarLevel(Integer starLevel)
    {
        this.starLevel = starLevel;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.equipped_wuxing_type
     *
     * @return the value of player_wuxing_card.equipped_wuxing_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getEquippedWuxingType()
    {
        return equippedWuxingType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.equipped_wuxing_type
     *
     * @param equippedWuxingType the value for player_wuxing_card.equipped_wuxing_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setEquippedWuxingType(Integer equippedWuxingType)
    {
        this.equippedWuxingType = equippedWuxingType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.is_equipped
     *
     * @return the value of player_wuxing_card.is_equipped
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Boolean getIsEquipped()
    {
        return isEquipped;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.is_equipped
     *
     * @param isEquipped the value for player_wuxing_card.is_equipped
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setIsEquipped(Boolean isEquipped)
    {
        this.isEquipped = isEquipped;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.is_ex
     *
     * @return the value of player_wuxing_card.is_ex
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Boolean getIsEx()
    {
        return isEx;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.is_ex
     *
     * @param isEx the value for player_wuxing_card.is_ex
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setIsEx(Boolean isEx)
    {
        this.isEx = isEx;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.base_exp
     *
     * @return the value of player_wuxing_card.base_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getBaseExp()
    {
        return baseExp;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.base_exp
     *
     * @param baseExp the value for player_wuxing_card.base_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setBaseExp(Integer baseExp)
    {
        this.baseExp = baseExp;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.used_exp
     *
     * @return the value of player_wuxing_card.used_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getUsedExp()
    {
        return usedExp;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.used_exp
     *
     * @param usedExp the value for player_wuxing_card.used_exp
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setUsedExp(Integer usedExp)
    {
        this.usedExp = usedExp;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.create_dt
     *
     * @return the value of player_wuxing_card.create_dt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Date getCreateDt()
    {
        return createDt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.create_dt
     *
     * @param createDt the value for player_wuxing_card.create_dt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setCreateDt(Date createDt)
    {
        this.createDt = createDt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_wuxing_card.last_update_dt
     *
     * @return the value of player_wuxing_card.last_update_dt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Date getLastUpdateDt()
    {
        return lastUpdateDt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_wuxing_card.last_update_dt
     *
     * @param lastUpdateDt the value for player_wuxing_card.last_update_dt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setLastUpdateDt(Date lastUpdateDt)
    {
        this.lastUpdateDt = lastUpdateDt;
    }
}