package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.Blobable;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;
@Table("player_task_level_battle_again")
public class PlayerTaskLevelBattleAgain implements Blobable<Entity.PlayerTaskLevelBattleAgainBlob>
{
    public Entity.PlayerTaskLevelBattleAgainBlob toBlob()
    {
        Entity.PlayerTaskLevelBattleAgainBlob.Builder blob = Entity.PlayerTaskLevelBattleAgainBlob.newBuilder();
        blob.setPlayerId(playerId);
        blob.setTaskLevelId(taskLevelId);
        blob.setLevelType(levelType);
        blob.setRemainingFightCnt(remainingFightCnt);
        return blob.build();
    }
    public void fromBlob(Entity.PlayerTaskLevelBattleAgainBlob blob)
    {
        this.playerId = blob.getPlayerId();
        this.taskLevelId = blob.getTaskLevelId();
        this.levelType = blob.getLevelType();
        this.remainingFightCnt = blob.getRemainingFightCnt();
    }
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_task_level_battle_again.id
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_task_level_battle_again.player_id_
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_task_level_battle_again.task_level_id_
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    @Column(name = "task_level_id_")
    private Integer taskLevelId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_task_level_battle_again.level_type
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    @Column(name = "level_type")
    private Integer levelType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column player_task_level_battle_again.remaining_fight_cnt
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    @Column(name = "remaining_fight_cnt")
    private Integer remainingFightCnt;
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_task_level_battle_again.id
     * @return the value of player_task_level_battle_again.id
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_task_level_battle_again.id
     * @param id  the value for player_task_level_battle_again.id
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_task_level_battle_again.player_id_
     * @return the value of player_task_level_battle_again.player_id_
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_task_level_battle_again.player_id_
     * @param playerId  the value for player_task_level_battle_again.player_id_
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_task_level_battle_again.task_level_id_
     * @return the value of player_task_level_battle_again.task_level_id_
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public Integer getTaskLevelId()
    {
        return taskLevelId;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_task_level_battle_again.task_level_id_
     * @param taskLevelId  the value for player_task_level_battle_again.task_level_id_
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public void setTaskLevelId(Integer taskLevelId)
    {
        this.taskLevelId = taskLevelId;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_task_level_battle_again.level_type
     * @return the value of player_task_level_battle_again.level_type
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public Integer getLevelType()
    {
        return levelType;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_task_level_battle_again.level_type
     * @param levelType  the value for player_task_level_battle_again.level_type
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public void setLevelType(Integer levelType)
    {
        this.levelType = levelType;
    }
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column player_task_level_battle_again.remaining_fight_cnt
     * @return the value of player_task_level_battle_again.remaining_fight_cnt
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public Integer getRemainingFightCnt()
    {
        return remainingFightCnt;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column player_task_level_battle_again.remaining_fight_cnt
     * @param remainingFightCnt  the value for player_task_level_battle_again.remaining_fight_cnt
     * @mbggenerated Sat Jul 20 16:35:44 CST 2013
     */
    public void setRemainingFightCnt(Integer remainingFightCnt)
    {
        this.remainingFightCnt = remainingFightCnt;
    }
}