package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.Blobable;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;

import java.util.Date;
@Table("player_event_sys")
public class PlayerEventSys implements Blobable<Entity.PlayerEventSysBlob>
{
    public Entity.PlayerEventSysBlob toBlob()
    {
        Entity.PlayerEventSysBlob.Builder blob = Entity.PlayerEventSysBlob.newBuilder();
        blob.setType(type);
        blob.setPlayerId(playerId);
        blob.setOtherPlayerId(otherPlayerId);
        blob.setOtherPlayerName(otherPlayerName);
        blob.setEventContent(eventContent);
        blob.setEventTime(eventTime.getTime());
        blob.setRefProcessId(refProcessId);
        blob.setIsProcessed(isProcessed);
        blob.setIsRead(isRead);
        blob.setItemType(itemType);
        blob.setItemId(itemId);
        blob.setItemAmt(itemAmt);
        blob.setGuajiNum(guajiNum);
        return blob.build();
    }
    public void fromBlob(Entity.PlayerEventSysBlob blob)
    {
        this.type = blob.getType();
        this.playerId = blob.getPlayerId();
        this.otherPlayerId = blob.getOtherPlayerId();
        this.otherPlayerName = blob.getOtherPlayerName();
        this.eventContent = blob.getEventContent();
        this.eventTime = new Date(blob.getEventTime());
        this.refProcessId = blob.getRefProcessId();
        this.isProcessed = blob.getIsProcessed();
        this.isRead = blob.getIsRead();
        this.itemType = blob.getItemType();
        this.itemId = blob.getItemId();
        this.itemAmt = blob.getItemAmt();
        this.guajiNum = blob.getGuajiNum();
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "type")
    private Integer type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.other_player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "other_player_id_")
    private Integer otherPlayerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.other_player_name
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "other_player_name")
    private String  otherPlayerName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.event_content
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "event_content")
    private String  eventContent;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.event_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "event_time")
    private Date eventTime = new Date();
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.ref_process_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "ref_process_id_")
    private Integer refProcessId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.is_processed
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "is_processed")
    private Boolean isProcessed;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.is_read
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "is_read")
    private Boolean isRead;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.item_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "item_type")
    private Integer itemType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.item_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "item_id_")
    private Integer itemId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.item_amt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "item_amt")
    private Integer itemAmt;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_event_sys.guaji_num
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    @Column(name = "guaji_num")
    private Integer guajiNum;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.id
     *
     * @return the value of player_event_sys.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.id
     *
     * @param id the value for player_event_sys.id
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.type
     *
     * @return the value of player_event_sys.type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getType()
    {
        return type;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.type
     *
     * @param type the value for player_event_sys.type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setType(Integer type)
    {
        this.type = type;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.player_id_
     *
     * @return the value of player_event_sys.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.player_id_
     *
     * @param playerId the value for player_event_sys.player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.other_player_id_
     *
     * @return the value of player_event_sys.other_player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getOtherPlayerId()
    {
        return otherPlayerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.other_player_id_
     *
     * @param otherPlayerId the value for player_event_sys.other_player_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setOtherPlayerId(Integer otherPlayerId)
    {
        this.otherPlayerId = otherPlayerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.other_player_name
     *
     * @return the value of player_event_sys.other_player_name
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public String getOtherPlayerName()
    {
        return otherPlayerName;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.other_player_name
     *
     * @param otherPlayerName the value for player_event_sys.other_player_name
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setOtherPlayerName(String otherPlayerName)
    {
        this.otherPlayerName = otherPlayerName == null ? null : otherPlayerName.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.event_content
     *
     * @return the value of player_event_sys.event_content
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public String getEventContent()
    {
        return eventContent;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.event_content
     *
     * @param eventContent the value for player_event_sys.event_content
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setEventContent(String eventContent)
    {
        this.eventContent = eventContent == null ? null : eventContent.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.event_time
     *
     * @return the value of player_event_sys.event_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Date getEventTime()
    {
        return eventTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.event_time
     *
     * @param eventTime the value for player_event_sys.event_time
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setEventTime(Date eventTime)
    {
        this.eventTime = eventTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.ref_process_id_
     *
     * @return the value of player_event_sys.ref_process_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getRefProcessId()
    {
        return refProcessId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.ref_process_id_
     *
     * @param refProcessId the value for player_event_sys.ref_process_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setRefProcessId(Integer refProcessId)
    {
        this.refProcessId = refProcessId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.is_processed
     *
     * @return the value of player_event_sys.is_processed
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Boolean getIsProcessed()
    {
        return isProcessed;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.is_processed
     *
     * @param isProcessed the value for player_event_sys.is_processed
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setIsProcessed(Boolean isProcessed)
    {
        this.isProcessed = isProcessed;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.is_read
     *
     * @return the value of player_event_sys.is_read
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Boolean getIsRead()
    {
        return isRead;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.is_read
     *
     * @param isRead the value for player_event_sys.is_read
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setIsRead(Boolean isRead)
    {
        this.isRead = isRead;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.item_type
     *
     * @return the value of player_event_sys.item_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getItemType()
    {
        return itemType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.item_type
     *
     * @param itemType the value for player_event_sys.item_type
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setItemType(Integer itemType)
    {
        this.itemType = itemType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.item_id_
     *
     * @return the value of player_event_sys.item_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getItemId()
    {
        return itemId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.item_id_
     *
     * @param itemId the value for player_event_sys.item_id_
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setItemId(Integer itemId)
    {
        this.itemId = itemId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.item_amt
     *
     * @return the value of player_event_sys.item_amt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getItemAmt()
    {
        return itemAmt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.item_amt
     *
     * @param itemAmt the value for player_event_sys.item_amt
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setItemAmt(Integer itemAmt)
    {
        this.itemAmt = itemAmt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_event_sys.guaji_num
     *
     * @return the value of player_event_sys.guaji_num
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public Integer getGuajiNum()
    {
        return guajiNum;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_event_sys.guaji_num
     *
     * @param guajiNum the value for player_event_sys.guaji_num
     *
     * @mbggenerated Thu Jun 27 17:09:25 CST 2013
     */
    public void setGuajiNum(Integer guajiNum)
    {
        this.guajiNum = guajiNum;
    }
}