package cn.teaey.test.load.entity;
import cn.teaey.fenrisulfr.orm.Blobable;
import cn.teaey.fenrisulfr.orm.annotation.Column;
import cn.teaey.fenrisulfr.orm.annotation.Table;

import java.util.Date;
@Table("player_guaji")
public class PlayerGuaji implements Blobable<Entity.PlayerGuajiBlob>
{
    public Entity.PlayerGuajiBlob toBlob()
    {
        Entity.PlayerGuajiBlob.Builder blob = Entity.PlayerGuajiBlob.newBuilder();
        blob.setPlayerId(playerId);
        blob.setLogicalServerId(logicalServerId);
        blob.setGuajiStartTime(guajiStartTime.getTime());
        blob.setGuajiTimeoutTime(guajiTimeoutTime.getTime());
        blob.setGuajiZoneId(guajiZoneId);
        blob.setGuajiDurationSec(guajiDurationSec);
        blob.setGuajiLastViewTime(guajiLastViewTime.getTime());
        blob.setGuajiMonsterCnt(guajiMonsterCnt);
        blob.setGuajiCoinGot(guajiCoinGot);
        blob.setGuajiExpGot(guajiExpGot);
        blob.setGuajiDropCnt(guajiDropCnt);
        blob.setGuajiYuanbaoGot(guajiYuanbaoGot);
        blob.setGuajiStatus(guajiStatus);
        blob.setGuajiStolenTimes(guajiStolenTimes);
        return blob.build();
    }
    public void fromBlob(Entity.PlayerGuajiBlob blob)
    {
        this.playerId = blob.getPlayerId();
        this.logicalServerId = blob.getLogicalServerId();
        this.guajiStartTime = new Date(blob.getGuajiStartTime());
        this.guajiTimeoutTime = new Date(blob.getGuajiTimeoutTime());
        this.guajiZoneId = blob.getGuajiZoneId();
        this.guajiDurationSec = blob.getGuajiDurationSec();
        this.guajiLastViewTime = new Date(blob.getGuajiLastViewTime());
        this.guajiMonsterCnt = blob.getGuajiMonsterCnt();
        this.guajiCoinGot = blob.getGuajiCoinGot();
        this.guajiExpGot = blob.getGuajiExpGot();
        this.guajiDropCnt = blob.getGuajiDropCnt();
        this.guajiYuanbaoGot = blob.getGuajiYuanbaoGot();
        this.guajiStatus = blob.getGuajiStatus();
        this.guajiStolenTimes = blob.getGuajiStolenTimes();
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.id
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "id", type = Column.ColumnType.KEY)
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.player_id_
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "player_id_")
    private Integer playerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.logical_server_id
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "logical_server_id")
    private Integer logicalServerId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_start_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_start_time")
    private Date guajiStartTime   = new Date();
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_timeout_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_timeout_time")
    private Date guajiTimeoutTime = new Date();
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_zone_id_
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_zone_id_")
    private Integer guajiZoneId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_duration_sec
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_duration_sec")
    private Integer guajiDurationSec;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_last_view_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_last_view_time")
    private Date guajiLastViewTime = new Date();
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_monster_cnt
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_monster_cnt")
    private Integer guajiMonsterCnt;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_coin_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_coin_got")
    private Integer guajiCoinGot;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_exp_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_exp_got")
    private Integer guajiExpGot;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_drop_cnt
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_drop_cnt")
    private Integer guajiDropCnt;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_yuanbao_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_yuanbao_got")
    private Integer guajiYuanbaoGot;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_status
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_status")
    private Integer guajiStatus;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_guaji.guaji_stolen_times
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    @Column(name = "guaji_stolen_times")
    private Integer guajiStolenTimes;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.id
     *
     * @return the value of player_guaji.id
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getId()
    {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.id
     *
     * @param id the value for player_guaji.id
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setId(Integer id)
    {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.player_id_
     *
     * @return the value of player_guaji.player_id_
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getPlayerId()
    {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.player_id_
     *
     * @param playerId the value for player_guaji.player_id_
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.logical_server_id
     *
     * @return the value of player_guaji.logical_server_id
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getLogicalServerId()
    {
        return logicalServerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.logical_server_id
     *
     * @param logicalServerId the value for player_guaji.logical_server_id
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setLogicalServerId(Integer logicalServerId)
    {
        this.logicalServerId = logicalServerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_start_time
     *
     * @return the value of player_guaji.guaji_start_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Date getGuajiStartTime()
    {
        return guajiStartTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_start_time
     *
     * @param guajiStartTime the value for player_guaji.guaji_start_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiStartTime(Date guajiStartTime)
    {
        this.guajiStartTime = guajiStartTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_timeout_time
     *
     * @return the value of player_guaji.guaji_timeout_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Date getGuajiTimeoutTime()
    {
        return guajiTimeoutTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_timeout_time
     *
     * @param guajiTimeoutTime the value for player_guaji.guaji_timeout_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiTimeoutTime(Date guajiTimeoutTime)
    {
        this.guajiTimeoutTime = guajiTimeoutTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_zone_id_
     *
     * @return the value of player_guaji.guaji_zone_id_
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiZoneId()
    {
        return guajiZoneId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_zone_id_
     *
     * @param guajiZoneId the value for player_guaji.guaji_zone_id_
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiZoneId(Integer guajiZoneId)
    {
        this.guajiZoneId = guajiZoneId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_duration_sec
     *
     * @return the value of player_guaji.guaji_duration_sec
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiDurationSec()
    {
        return guajiDurationSec;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_duration_sec
     *
     * @param guajiDurationSec the value for player_guaji.guaji_duration_sec
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiDurationSec(Integer guajiDurationSec)
    {
        this.guajiDurationSec = guajiDurationSec;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_last_view_time
     *
     * @return the value of player_guaji.guaji_last_view_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Date getGuajiLastViewTime()
    {
        return guajiLastViewTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_last_view_time
     *
     * @param guajiLastViewTime the value for player_guaji.guaji_last_view_time
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiLastViewTime(Date guajiLastViewTime)
    {
        this.guajiLastViewTime = guajiLastViewTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_monster_cnt
     *
     * @return the value of player_guaji.guaji_monster_cnt
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiMonsterCnt()
    {
        return guajiMonsterCnt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_monster_cnt
     *
     * @param guajiMonsterCnt the value for player_guaji.guaji_monster_cnt
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiMonsterCnt(Integer guajiMonsterCnt)
    {
        this.guajiMonsterCnt = guajiMonsterCnt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_coin_got
     *
     * @return the value of player_guaji.guaji_coin_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiCoinGot()
    {
        return guajiCoinGot;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_coin_got
     *
     * @param guajiCoinGot the value for player_guaji.guaji_coin_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiCoinGot(Integer guajiCoinGot)
    {
        this.guajiCoinGot = guajiCoinGot;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_exp_got
     *
     * @return the value of player_guaji.guaji_exp_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiExpGot()
    {
        return guajiExpGot;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_exp_got
     *
     * @param guajiExpGot the value for player_guaji.guaji_exp_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiExpGot(Integer guajiExpGot)
    {
        this.guajiExpGot = guajiExpGot;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_drop_cnt
     *
     * @return the value of player_guaji.guaji_drop_cnt
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiDropCnt()
    {
        return guajiDropCnt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_drop_cnt
     *
     * @param guajiDropCnt the value for player_guaji.guaji_drop_cnt
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiDropCnt(Integer guajiDropCnt)
    {
        this.guajiDropCnt = guajiDropCnt;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_yuanbao_got
     *
     * @return the value of player_guaji.guaji_yuanbao_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiYuanbaoGot()
    {
        return guajiYuanbaoGot;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_yuanbao_got
     *
     * @param guajiYuanbaoGot the value for player_guaji.guaji_yuanbao_got
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiYuanbaoGot(Integer guajiYuanbaoGot)
    {
        this.guajiYuanbaoGot = guajiYuanbaoGot;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_status
     *
     * @return the value of player_guaji.guaji_status
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiStatus()
    {
        return guajiStatus;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_status
     *
     * @param guajiStatus the value for player_guaji.guaji_status
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiStatus(Integer guajiStatus)
    {
        this.guajiStatus = guajiStatus;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_guaji.guaji_stolen_times
     *
     * @return the value of player_guaji.guaji_stolen_times
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public Integer getGuajiStolenTimes()
    {
        return guajiStolenTimes;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_guaji.guaji_stolen_times
     *
     * @param guajiStolenTimes the value for player_guaji.guaji_stolen_times
     *
     * @mbggenerated Sun Jul 21 17:20:08 CST 2013
     */
    public void setGuajiStolenTimes(Integer guajiStolenTimes)
    {
        this.guajiStolenTimes = guajiStolenTimes;
    }
}